//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "auth_sessions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub realm_id: Uuid,
    pub client_id: Uuid,
    pub redirect_uri: String,
    pub response_type: String,
    pub scope: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub state: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub nonce: Option<String>,
    pub user_id: Option<Uuid>,
    #[sea_orm(unique)]
    pub code: Option<String>,
    pub authenticated: bool,
    pub created_at: DateTime,
    pub expires_at: DateTime,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub webauthn_challenge: Option<Json>,
    pub webauthn_challenge_issued_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::clients::Entity",
        from = "Column::ClientId",
        to = "super::clients::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Clients,
    #[sea_orm(
        belongs_to = "super::realms::Entity",
        from = "Column::RealmId",
        to = "super::realms::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Realms,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "(Column::UserId, Column::UserId)",
        to = "(super::users::Column::Id, super::users::Column::Id)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::clients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clients.def()
    }
}

impl Related<super::realms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Realms.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
