//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "realms")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub name: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::auth_sessions::Entity")]
    AuthSessions,
    #[sea_orm(has_many = "super::clients::Entity")]
    Clients,
    #[sea_orm(has_many = "super::jwt_keys::Entity")]
    JwtKeys,
    #[sea_orm(has_many = "super::magic_links::Entity")]
    MagicLinks,
    #[sea_orm(has_many = "super::realm_settings::Entity")]
    RealmSettings,
    #[sea_orm(has_many = "super::roles::Entity")]
    Roles,
    #[sea_orm(has_many = "super::security_events::Entity")]
    SecurityEvents,
    #[sea_orm(has_many = "super::user_sessions::Entity")]
    UserSessions,
    #[sea_orm(has_many = "super::users::Entity")]
    Users,
    #[sea_orm(has_many = "super::webhooks::Entity")]
    Webhooks,
}

impl Related<super::auth_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthSessions.def()
    }
}

impl Related<super::clients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clients.def()
    }
}

impl Related<super::jwt_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::JwtKeys.def()
    }
}

impl Related<super::magic_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MagicLinks.def()
    }
}

impl Related<super::realm_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RealmSettings.def()
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Roles.def()
    }
}

impl Related<super::security_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SecurityEvents.def()
    }
}

impl Related<super::user_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserSessions.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::webhooks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Webhooks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
